GET http://localhost:3000/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNDBkMzVmMy01ODU1LTQxMzItYTc3Mi1lZTlkMGE5ZGEzNmYiLCJlbWFpbCI6IkhhcnZleUBnbWFpbC5jb20iLCJpYXQiOjE3NTI2NjgzMTh9.6IXJj85MEE0XC6-l1xL5q533_2bziMOUzsgOk7uGSz8